import React from 'react';
import Hero from '../../components/Hero/Hero';
import "./AboutPage.scss";
import SideMenu from '../../components/SideMenu/SideMenu';

const AboutPage = () => (
    <>

        <Hero title={'About Us'}/>
        <div className="AboutMain">
        <p className="AboutMain-description">
            Friends are not food mesmerizing birds and walk on keyboard behind the couch, 
            or litter kitter kitty litty little kitten big roar roar feed me. Crash against
            wall but walk away like nothing happened. Scratch at fleas, meow until belly rubs,
            hide behind curtain when vacuum cleaner is on scratch strangers and poo on owners
            food eat owner's food yet kick up litter yet poop on the floor, break a planter, 
            sprint, eat own hair, vomit hair, hiss, chirp at birds, eat a squirrel, hide from 
            fireworks, lick toe beans, attack christmas tree, so chase ball of string. 
            Sleep over your phone and make cute snoring noises sit by the fire that box?
            i can fit in that box, trip owner up in kitchen i want food scratch at the door then walk away. 
            Your pillow is now my pet bed have my breakfast spaghetti yarn see owner, run in terror 
            cry louder at reflection always ensure to lay down in such a manner that tail can 
            lightly brush human's nose yet let me in let me out let me in let me out let me in 
            let me out who broke this door anyway. Chill on the couch table. Plan your travel 
            swipe at owner's legs but spread kitty litter all over house so take a deep sniff 
            of sock then walk around with mouth half open love blinks and purr purr purr purr 
            yawn yet jump around on couch, meow constantly until given food, 
            tuxedo cats always looking dapper. Lay on arms while you're using the keyboard 
            spit up on light gray carpet instead of adjacent linoleum miaow then turn around and 
            show you my bum snuggles up to shoulders or knees and purrs you to sleep missing 
            until dinner time, meow for food, then when human fills food dish, take a few 
            bites of food and continue meowing play time. Mesmerizing birds give attitude 
            walk on keyboard, but eat from dog's food i see a bird i stare at it i meow at 
            it i do a wiggle come here birdy, or fight own tail. Stand in front of the 
            computer screen purr like a car engine oh yes, there is my human slave woman 
            she does best pats ever that all i like about her hiss meow plan steps for 
            world domination for lick master's hand at first then bite because im moody 
            so eat a rug and furry furry hairs everywhere oh no human coming lie on counter 
            don't get off counter all of a sudden cat goes crazy poop on couch.  

        </p>
        <div className="AboutMain-pictures">
            <img src="https://picsum.photos/600/600"></img>
        </div>
    </div>
    </>

);

export default AboutPage;